# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Events"
  url = "#events"
  weight = 20

[[main]]
  name = "Speaking"
  url = "#speaking"
  weight = 30

[[main]]
  name = "Sponsors"
  url = "sponsors"
  weight = 40

[[main]]
  name = "Organisers"
  url = "#"
  hasChildren = true
  weight = 50

[[main]]
  parent = "Organisers"
  name = "Sarah"
  url = "#sarah"
  weight = 10

[[main]]
  parent = "Organisers"
  name = "Gregor"
  url = "#gregor"
  weight = 20

[[main]]
  name = "Newsletter"
  url = "#newsletter"
  weight = 60

[[main]]
  name = "Past Events"
  url = "#"
  hasChildren = true
  weight = 70

[[main]]
  parent = "Past Events"
  name = "2017"
  url = "2017"
  weight = 10

[[main]]
  parent = "Past Events"
  name = "2018"
  url = "2018"
  weight = 20

[[main]]
  parent = "Past Events"
  name = "2019"
  url = "2019"
  weight = 30

[[main]]
  parent = "Past Events"
  name = "2020"
  url = "2020"
  weight = 40

[[main]]
  parent = "Past Events"
  name = "2021"
  url = "2021"
  weight = 50

[[main]]
  parent = "Past Events"
  name = "2022"
  url = "2022"
  weight = 60

[[main]]
  parent = "Past Events"
  name = "2023"
  url = "2023"
  weight = 70

[[main]]
  parent = "Past Events"
  name = "2024"
  url = "2024"
  weight = 80

[[main]]
  name = "Code of Conduct"
  url = "conduct"
  weight = 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
