baseURL = "http://example.org/"
title = "Glasgow Azure User Group"

theme = "academia-hugo"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[params]
author = "Sarah Lean"
description =  "Glasgow Azure User Group"
keywords = "glasgow, azure, user group, community"
info = "Glasgow Azure User Group"
