name: Deploy Hugo Site to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull request to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: 'latest'

    - name: Build the site
      run: hugo --minify

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.3

      with:
        name: hugo-site
        path: public

